### ISSUE TITLE
About CoilImage

### ISSUE THREAD

**Issue by CMingTseng** [chrisbanes/tivi#813]
Dear Sir

sorry i know CoilImage not in this project 

but i can not find  https://github.com/chrisbanes/accompanist/ 

Ref : https://mvnrepository.com/artifact/dev.chrisbanes.accompanist/accompanist-coil/0.6.2

i know accompanist-coil base on compose 1.0.0-beta02

now compose library is 1.0.0-beta08 

as ref :  https://developer.android.com/jetpack/androidx/releases/compose-runtime#1.0.0-beta07

Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)

how can find new version  CoilImage ?

https://google.github.io/accompanist/coil/migration-coilimage/

THX

**Comment by chrisbanes** [comment]
This isn’t anything to do with Tivi, and you’ve already linked to the necessary documentation.
